@extends('layouts.appmain')
@section('content')
	@include('inc.about')
	@include('inc.features')
	@include('inc.team')
	@include('inc.clients')
	@include('inc.portfolio')
	@include('inc.contact')
@endsection
